# Generated by Django 2.2.17 on 2020-12-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paket',
            name='hari',
        ),
        migrations.DeleteModel(
            name='hari',
        ),
        migrations.DeleteModel(
            name='paket',
        ),
    ]
