# Generated by Django 2.2.17 on 2020-12-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20201216_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pkt', models.IntegerField(blank=True, null=True)),
                ('id_pkt', models.IntegerField(null=True)),
                ('nama_pkt', models.CharField(max_length=200, null=True)),
                ('jml_pertemuan', models.IntegerField(null=True)),
                ('biaya', models.IntegerField(null=True)),
                ('hari_1', models.CharField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], max_length=200)),
                ('Jam_1', models.CharField(blank=True, choices=[(1, '07-08 AM'), (2, '08-09 AM'), (3, '09-10 AM'), (4, '10-11 AM'), (5, '11-12 PM')], max_length=200)),
                ('hari_2', models.CharField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], max_length=200)),
                ('Jam_2', models.CharField(blank=True, choices=[(1, '07-08 AM'), (2, '08-09 AM'), (3, '09-10 AM'), (4, '10-11 AM'), (5, '11-12 PM')], max_length=200)),
                ('hari_3', models.CharField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], max_length=200)),
                ('Jam_3', models.CharField(blank=True, choices=[(1, '07-08 AM'), (2, '08-09 AM'), (3, '09-10 AM'), (4, '10-11 AM'), (5, '11-12 PM')], max_length=200)),
                ('hari_4', models.CharField(blank=True, choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')], max_length=200)),
                ('Jam_4', models.CharField(blank=True, choices=[(1, '07-08 AM'), (2, '08-09 AM'), (3, '09-10 AM'), (4, '10-11 AM'), (5, '11-12 PM')], max_length=200)),
            ],
        ),
    ]
