# Generated by Django 2.2.17 on 2020-12-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_paket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paket',
            old_name='Jam_1',
            new_name='jam_1',
        ),
        migrations.RenameField(
            model_name='paket',
            old_name='Jam_2',
            new_name='jam_2',
        ),
        migrations.RenameField(
            model_name='paket',
            old_name='Jam_3',
            new_name='jam_3',
        ),
        migrations.RenameField(
            model_name='paket',
            old_name='Jam_4',
            new_name='jam_4',
        ),
    ]
