# Generated by Django 2.2.17 on 2020-12-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20201216_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='hari_1',
            field=models.CharField(blank=True, choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu'), ('7', 'Minggu')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='hari_2',
            field=models.CharField(blank=True, choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu'), ('7', 'Minggu')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='hari_3',
            field=models.CharField(blank=True, choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu'), ('7', 'Minggu')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='hari_4',
            field=models.CharField(blank=True, choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu'), ('7', 'Minggu')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='jam_1',
            field=models.CharField(blank=True, choices=[('1', '07-08 AM'), ('2', '08-09 AM'), ('3', '09-10 AM'), ('4', '10-11 AM'), ('5', '11-12 PM')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='jam_2',
            field=models.CharField(blank=True, choices=[('1', '07-08 AM'), ('2', '08-09 AM'), ('3', '09-10 AM'), ('4', '10-11 AM'), ('5', '11-12 PM')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='jam_3',
            field=models.CharField(blank=True, choices=[('1', '07-08 AM'), ('2', '08-09 AM'), ('3', '09-10 AM'), ('4', '10-11 AM'), ('5', '11-12 PM')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='jam_4',
            field=models.CharField(blank=True, choices=[('1', '07-08 AM'), ('2', '08-09 AM'), ('3', '09-10 AM'), ('4', '10-11 AM'), ('5', '11-12 PM')], max_length=200),
        ),
        migrations.AlterField(
            model_name='paket',
            name='jml_pertemuan',
            field=models.CharField(blank=True, choices=[('1', '1X Pertemuan'), ('2', '2X Pertemuan'), ('3', '3X Pertemuan'), ('4', '4X Pertemuan')], max_length=200, null=True),
        ),
    ]
