# Generated by Django 2.2.17 on 2020-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20201217_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataguru',
            name='kelamin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datamurid',
            name='kelamin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
