# Generated by Django 2.2.17 on 2020-12-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20201217_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataguru',
            name='kelamin',
        ),
        migrations.RemoveField(
            model_name='datamurid',
            name='kelamin',
        ),
    ]
