# Generated by Django 2.2.17 on 2020-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_auto_20201218_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataguru',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='datamurid',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
    ]
